import { activeBranding } from '../config/branding';
import { designColors, fontSizes, radii, spacing } from './tokens';

export const palette = {
    // Brand Colors
    magenta: activeBranding.colors.primary,
    purple: activeBranding.colors.secondary,
    violet: activeBranding.colors.secondary,
    cyan: activeBranding.colors.accent,
    fuchsia: activeBranding.colors.secondary,
    lime: activeBranding.colors.success,

    // Neutrals Light
    text: activeBranding.colors.text,
    textMuted: activeBranding.colors.textMuted,
    textSoft: activeBranding.colors.textSoft,
    border: activeBranding.colors.border,
    background: activeBranding.colors.background,
    surface: activeBranding.colors.surface,

    // Neutrals Dark
    darkBackground: activeBranding.colors.darkBackground,
    darkSurface: activeBranding.colors.darkSurface,
    darkSurfaceAlt: activeBranding.colors.darkSurfaceAlt,
    darkText: activeBranding.colors.darkText,
    darkTextMuted: activeBranding.colors.darkTextMuted,
    darkBorder: activeBranding.colors.darkBorder,

    // System
    error: activeBranding.colors.danger || '#C70036',
    danger: activeBranding.colors.danger || '#C70036',
    warning: activeBranding.colors.warning,
    success: activeBranding.colors.success,
    white: '#FFFFFF',
    black: '#000000',
};

export const lightTheme = {
    mode: 'light',
    colors: {
        primary: palette.magenta,
        secondary: palette.purple,
        accent: palette.cyan,
        success: palette.success,
        background: palette.background,
        surface: palette.surface,
        surfaceAlt: activeBranding.colors.surfaceAlt || '#F9FAFB',
        surfaceRaised: activeBranding.colors.surfaceRaised || activeBranding.colors.surface,
        text: palette.text,
        textMuted: palette.textMuted,
        textSoft: palette.textSoft,
        border: palette.border,
        borderStrong: activeBranding.colors.borderStrong || palette.border,
        brandSoft: activeBranding.colors.brandSoft || designColors.bgBrandSoft,
        brandMedium: activeBranding.colors.brandMedium || designColors.bgBrandMedium,
        successSoft: activeBranding.colors.successSoft || designColors.successSoft,
        warningSoft: activeBranding.colors.warningSoft || '#FFF4D6',
        danger: palette.danger,
        dangerSoft: activeBranding.colors.dangerSoft || '#FEF0F2',
        icon: activeBranding.colors.icon,
        warning: palette.warning,
        white: designColors.white,
        black: designColors.black,
        shadow: designColors.shadow,
        gradients: activeBranding.gradients,
        auth: {
            glow: activeBranding.colors.authGlow,
            networkLine: activeBranding.colors.authNetworkLine,
            nodeOuter: activeBranding.colors.authNodeOuter,
            nodeInner: activeBranding.colors.authNodeInner,
            grid: activeBranding.colors.authGrid,
            blobA: activeBranding.colors.authBlobA,
            blobB: activeBranding.colors.authBlobB,
            blobC: activeBranding.colors.authBlobC,
        },
        button: {
            secondary: {
                text: activeBranding.colors.buttonSecondaryText,
                bg: activeBranding.colors.buttonSecondaryBg,
                border: activeBranding.colors.buttonSecondaryBorder,
                hoverBg: activeBranding.colors.buttonSecondaryHoverBg,
            },
            tertiary: {
                text: activeBranding.colors.buttonTertiaryText,
                bg: activeBranding.colors.buttonTertiaryBg,
                border: activeBranding.colors.buttonTertiaryBorder,
                hoverText: activeBranding.colors.buttonTertiaryHoverText,
                hoverBg: activeBranding.colors.buttonTertiaryHoverBg,
                hoverBorder: activeBranding.colors.buttonTertiaryHoverBorder,
                focusText: activeBranding.colors.buttonTertiaryFocusText,
                focusBg: activeBranding.colors.buttonTertiaryFocusBg,
                focusBorder: activeBranding.colors.buttonTertiaryFocusBorder,
            },
            disabled: {
                bg: activeBranding.colors.buttonDisabledBg,
                border: activeBranding.colors.buttonDisabledBorder,
                text: activeBranding.colors.buttonDisabledText,
            },
        },
    },
    fontSizes,
    radii,
    spacing,
};

export const darkTheme = {
    mode: 'dark',
    colors: {
        primary: activeBranding.colors.primary,
        secondary: activeBranding.colors.secondary,
        accent: activeBranding.colors.accent,
        success: activeBranding.colors.success,
        background: activeBranding.colors.darkBackground,
        surface: activeBranding.colors.darkSurface,
        surfaceAlt: activeBranding.colors.darkSurfaceAlt,
        surfaceRaised: activeBranding.colors.darkSurface,
        text: activeBranding.colors.darkText,
        textMuted: activeBranding.colors.darkTextMuted,
        textSoft: activeBranding.colors.darkTextSoft,
        border: activeBranding.colors.darkBorder,
        borderStrong: activeBranding.colors.borderStrong || activeBranding.colors.darkBorder,
        brandSoft: designColors.darkBgTertiary,
        brandMedium: designColors.darkBgTertiary,
        successSoft: designColors.darkBgTertiary,
        warningSoft: designColors.darkBgTertiary,
        danger: activeBranding.colors.danger || '#C70036',
        dangerSoft: designColors.darkBgTertiary,
        icon: activeBranding.colors.secondary,
        warning: activeBranding.colors.warning,
        white: designColors.white,
        black: designColors.black,
        shadow: designColors.shadow,
        gradients: activeBranding.gradients,
        auth: {
            glow: activeBranding.colors.authGlow,
            networkLine: activeBranding.colors.authNetworkLine,
            nodeOuter: activeBranding.colors.authNodeOuter,
            nodeInner: activeBranding.colors.authNodeInner,
            grid: activeBranding.colors.authGrid,
            blobA: activeBranding.colors.authBlobA,
            blobB: activeBranding.colors.authBlobB,
            blobC: activeBranding.colors.authBlobC,
        },
        button: {
            secondary: {
                text: activeBranding.colors.buttonSecondaryText,
                bg: activeBranding.colors.buttonSecondaryBg,
                border: activeBranding.colors.buttonSecondaryBorder,
                hoverBg: activeBranding.colors.buttonSecondaryHoverBg,
            },
            tertiary: {
                text: activeBranding.colors.buttonTertiaryText,
                bg: activeBranding.colors.buttonTertiaryBg,
                border: activeBranding.colors.buttonTertiaryBorder,
                hoverText: activeBranding.colors.buttonTertiaryHoverText,
                hoverBg: activeBranding.colors.buttonTertiaryHoverBg,
                hoverBorder: activeBranding.colors.buttonTertiaryHoverBorder,
                focusText: activeBranding.colors.buttonTertiaryFocusText,
                focusBg: activeBranding.colors.buttonTertiaryFocusBg,
                focusBorder: activeBranding.colors.buttonTertiaryFocusBorder,
            },
            disabled: {
                bg: activeBranding.colors.buttonDisabledBg,
                border: activeBranding.colors.buttonDisabledBorder,
                text: activeBranding.colors.buttonDisabledText,
            },
        },
    },
    fontSizes,
    radii,
    spacing,
};
