import { designColors, gradients } from '../theme/tokens';

const BRANDING_PROFILES = {
  default: {
    applicationName: 'Relevamiento Chaco',
    loginSubtitle: 'Inicia sesion para continuar',
    registerSubtitle: 'Unite a Relevamiento Chaco',
    assets: {
      logo: require('../../assets/brand/logo-chaco.png'),
      miniLogo: require('../../assets/brand/mini-logo-chaco.png'),
      bannerBackground: require('../../assets/images/back_banner.jpg'),
    },
    banner: {
      mode: 'image',
      color: '#FF0080',
    },
    colors: {
      primary: '#FF0080',
      secondary: '#7928CA',
      accent: '#08B8CC',
      success: '#2DCE89',
      warning: '#FFB020',
      danger: '#EA0606',
      text: '#252F40',
      textMuted: '#67748E',
      textSoft: '#8392AB',
      border: '#E9ECEF',
      borderStrong: '#4A5565',
      background: '#F8F9FA',
      surface: '#FFFFFF',
      surfaceAlt: '#F9FAFB',
      surfaceRaised: '#FFFFFF',
      brandSoft: 'rgba(255, 0, 128, 0.10)',
      brandMedium: 'rgba(255, 0, 128, 0.16)',
      successSoft: 'rgba(45, 206, 137, 0.12)',
      successMedium: 'rgba(45, 206, 137, 0.20)',
      warningSoft: 'rgba(255, 176, 32, 0.12)',
      warningMedium: 'rgba(255, 176, 32, 0.20)',
      dangerSoft: '#FEE2E2',
      dangerMedium: '#FECACA',
      darkBackground: '#101828',
      darkSurface: '#1C293A',
      darkSurfaceAlt: '#252F40',
      darkText: '#FFFFFF',
      darkTextMuted: '#E5E7EB',
      darkTextSoft: '#8C8C8C',
      darkBorder: '#4A5565',
      icon: '#56606A',
      buttonSecondaryText: '#4A5565',
      buttonSecondaryBg: '#F9FAFB',
      buttonSecondaryBorder: '#E5E7EB',
      buttonSecondaryHoverBg: '#F3F4F6',
      buttonTertiaryText: '#FF0080',
      buttonTertiaryBg: '#FFFFFF',
      buttonTertiaryBorder: '#FF0080',
      buttonTertiaryHoverText: '#D4006A',
      buttonTertiaryHoverBg: 'rgba(255, 0, 128, 0.10)',
      buttonTertiaryHoverBorder: '#D4006A',
      buttonTertiaryFocusText: '#D4006A',
      buttonTertiaryFocusBg: 'rgba(212, 0, 106, 0.10)',
      buttonTertiaryFocusBorder: '#D4006A',
      buttonDisabledBg: '#F3F4F6',
      buttonDisabledBorder: '#E5E7EB',
      buttonDisabledText: '#99A1AF',
      authGlow: '#FF0080',
      authNetworkLine: 'rgba(180, 32, 176, 0.35)',
      authNodeOuter: 'rgba(255, 0, 128, 0.18)',
      authNodeInner: 'rgba(255, 0, 128, 0.9)',
      authGrid: 'rgba(255, 0, 128, 0.07)',
      authBlobA: 'rgba(255, 0, 128, 0.18)',
      authBlobB: 'rgba(121, 40, 202, 0.16)',
      authBlobC: 'rgba(137, 8, 204, 0.14)',
    },
    gradients: {
      brand: ['#FF0080', '#7928CA'],
      buttonPrimary: ['#7828CA', '#FF0080'],
      buttonPrimaryPressedOverlay: 'rgba(0, 0, 0, 0.20)',
    },
  },
  chaco: {
    applicationName: 'Relevamiento Chaco',
    loginSubtitle: 'Iniciá sesión para continuar',
    registerSubtitle: 'Unite a Relevamiento Chaco',
    assets: {
      logo: require('../../assets/brand/logo-chaco.png'),
      miniLogo: require('../../assets/brand/mini-logo-chaco.png'),
      bannerBackground: require('../../assets/images/back_banner.jpg'),
    },
    banner: {
      mode: 'solid',
      color: designColors.brand,
    },
    colors: {
      primary: designColors.brand,
      secondary: designColors.pink,
      accent: designColors.accent,
      success: designColors.success,
      warning: designColors.warning,
      danger: designColors.danger,
      text: designColors.textHeading,
      textMuted: designColors.textBody,
      textSoft: designColors.textBodySubtle,
      border: designColors.borderBase,
      borderStrong: designColors.borderDark,
      background: designColors.bgSecondary,
      surface: designColors.bgPrimary,
      surfaceAlt: designColors.bgTertiary,
      surfaceRaised: designColors.bgPrimary,
      brandSoft: designColors.bgBrandSoft,
      brandMedium: designColors.bgBrandMedium,
      successSoft: designColors.successSoft,
      successMedium: designColors.successMedium,
      warningSoft: designColors.warningSoft,
      warningMedium: designColors.warningMedium,
      dangerSoft: designColors.dangerSoft,
      dangerMedium: designColors.dangerMedium,
      darkBackground: designColors.darkBgPrimary,
      darkSurface: designColors.darkBgSecondary,
      darkSurfaceAlt: designColors.darkBgTertiary,
      darkText: designColors.darkTextHeading,
      darkTextMuted: designColors.darkTextBody,
      darkTextSoft: designColors.darkTextBody,
      darkBorder: designColors.darkBorder,
      icon: designColors.brand,
      buttonSecondaryText: designColors.textBody,
      buttonSecondaryBg: designColors.bgSecondary,
      buttonSecondaryBorder: designColors.borderBase,
      buttonSecondaryHoverBg: designColors.bgTertiary,
      buttonTertiaryText: designColors.brand,
      buttonTertiaryBg: designColors.bgPrimary,
      buttonTertiaryBorder: designColors.brand,
      buttonTertiaryHoverText: designColors.brand,
      buttonTertiaryHoverBg: designColors.bgBrandSoft,
      buttonTertiaryHoverBorder: designColors.brand,
      buttonTertiaryFocusText: designColors.brandStrong,
      buttonTertiaryFocusBg: designColors.bgBrandSoft,
      buttonTertiaryFocusBorder: designColors.brandStrong,
      buttonDisabledBg: designColors.disabledBg,
      buttonDisabledBorder: designColors.borderBase,
      buttonDisabledText: designColors.disabledText,
      authGlow: designColors.brand,
      authNetworkLine: 'rgba(80, 89, 188, 0.35)',
      authNodeOuter: 'rgba(80, 89, 188, 0.20)',
      authNodeInner: 'rgba(249, 141, 255, 0.95)',
      authGrid: 'rgba(80, 89, 188, 0.08)',
      authBlobA: 'rgba(80, 89, 188, 0.16)',
      authBlobB: 'rgba(249, 141, 255, 0.14)',
      authBlobC: 'rgba(200, 210, 156, 0.14)',
    },
    gradients: {
      brand: gradients.brand,
      buttonPrimary: gradients.buttonPrimary,
      buttonPrimaryPressedOverlay: gradients.buttonPrimaryPressedOverlay,
    },
  },
};

const ACTIVE_PROFILE = process.env.EXPO_PUBLIC_APP_PRESENTATION || 'chaco';

export const activeBranding = BRANDING_PROFILES[ACTIVE_PROFILE] || BRANDING_PROFILES.default;
export const activeBrandProfile = BRANDING_PROFILES[ACTIVE_PROFILE] ? ACTIVE_PROFILE : 'default';
export { BRANDING_PROFILES };
